Validator rewards distribution
chain4travel/caminogo pull request #162
Opened 2023-01-23 16:51 UTC by evlekht

## Why this should be merged

## How this works

## How this was tested

2023-01-24 15:02 UTC, charalarg commented on vms/platformvm/txs/executor/camino_state_changes.go
> +		newNotDistributedAmount := amountToDistribute - addedReward*uint64(validators.Len())
Maybe replace this calculation with % calculation for better readability?

2023-01-25 15:38 UTC, c4t-ag requested changes

2023-01-25 15:38 UTC, c4t-ag commented on vms/platformvm/state/camino.go
> +	rewardsDB database.Database
Suggestion: claimableDB

2023-01-25 15:38 UTC, c4t-ag commented on vms/platformvm/state/camino_rewards.go
> +	Owner           *secp256k1fx.OutputOwners
serialize?

2023-01-25 17:27 UTC, c4t-ag approved these changes

2023-01-26 10:18 UTC, merged