[API] Introduced new platform API for retrieving all deposit offers
chain4travel/caminogo pull request #181
Opened 2023-02-14 11:45 UTC by knikos

## Why this should be merged
To facilitate the retrieval of necessary information regarding deposit offers and thus the issuing of a deposit Tx.

## How this works
Introduces a new platform API `GetAllDepositOffers` . The API offers a single optional input arg `Active` to allow for filtering of deposit offers.

## How this was tested
By manually calling the API.

2023-02-14 12:54 UTC, knikos commented
Note that the field memo is returned base64 encoded. Decoding is expected to take place on the consumer's end.

2023-02-15 06:30 UTC, c4t-ag requested changes
Pls. add example Request and response JSON in PR description

2023-02-15 07:33 UTC, knikos commented
> Pls. add example Request and response JSON in PR description

done

2023-02-15 08:51 UTC, c4t-ag approved these changes

2023-02-15 08:52 UTC, merged