[PVM] MultisigAliasTx implementation
chain4travel/caminogo pull request #246
Opened 2023-04-28 13:34 UTC by charalarg

## Description ##

This PR implements the logic of the creation of a new multisig alias definition and the update of an existing ones by the `multisigAliasTx`.  It was developed under the requirements bellow:

- Adding a new multisig alias does only require the signature of the owner issuing the transaction
- Updating an existing multisig alias require as many signature as the threshold of the alias

## Changes ##

- Added the `mutlistigAliasTx` Implementation in the `camino_tx_executor`
- Added the `mutlistigAliasTx` Implementation in the `camino_builder`
- Implemented the equivalent service
- Minor naming and error handling optimizations
- Implemented unit tests for the executor's logic
- Minor changes on helper functions

## Remarks ##

Both builder and service were implemented only for manual testing purposes. We need to refine further if we need to involve them in the PR.

2023-05-02 15:59 UTC, evlekht requested changes

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/camino_service.go
> +		alias = ids.ShortEmpty
I think that zero-value == empty already

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/metrics/camino_tx_metrics.go
> +		numMultisigAliasTx:  newTxMetric(namespace, "multisig_alias", registerer, &errs),
```suggestion
		numMultisigAliasTxs:  newTxMetric(namespace, "multisig_alias", registerer, &errs),
```

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/metrics/camino_tx_metrics.go
> +	m.numBaseTxs.Inc()
typo

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/builder/camino_builder.go
> +		addrs := []ids.ShortID{multisigAlias.ID}
addrs implies that there are multiple addresses, suggest to rename it, its really confusing

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/builder/camino_builder.go
> +		Auth:          &secp256k1fx.Input{SigIndices: sigIndices},
just use in.Input

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/camino_multisig_alias_tx.go
> +	Auth verify.Verifiable `serialize:"true" json:"authorization"`
suggest to make field name match json tag

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/camino_multisig_alias_tx.go
>  	MultisigAlias multisig.Alias `serialize:"true"`
add json tag, so we'll display tx json properly

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/camino_multisig_alias_tx.go
> +	ErrFailedToVerifyOwnerOrAuth            = fmt.Errorf("failed to verify owner or auth")
```suggestion
	ErrFailedToVerifyAliasOrAuth            = errors.New("failed to verify alias or auth")
```

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/executor/camino_tx_executor.go
> +	var aliasID ids.ShortID
I'd suggest to move all this to previous if-else `tx.MultisigAlias.ID != ids.ShortEmpty`
We can also then move `var alias *multisig.AliasWithNonce` inside if

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/executor/camino_tx_executor.go
> +	e.State.SetMultisigAlias(newAlias)
```suggestion
	e.State.SetMultisigAlias(&multisig.AliasWithNonce{
		Alias: multisig.Alias{
			ID:     aliasID,
			Memo:   tx.MultisigAlias.Memo,
			Owners: tx.MultisigAlias.Owners,
		},
		Nonce: nonce,
	})
```

2023-05-02 15:59 UTC, evlekht commented on vms/platformvm/txs/executor/camino_tx_executor_test.go
> +		"updating existing alias with unordered owners": {
thats syntactic, move it to dedicated test, plz (and you can also make error non-exported then)
some for other syntactic tests below - no need to list them here

2023-05-02 15:59 UTC, evlekht commented on wallet/chain/p/camino_visitor.go
> +func (s *signerVisitor) MultisigAliasTx(tx *txs.MultisigAliasTx) error {
plz add comment in my PR https://github.com/chain4travel/caminogo/pull/170, so this won't be lost
this impl isn't taking into account existing alias signers case

2023-05-03 07:33 UTC, charalarg commented on vms/platformvm/txs/builder/camino_builder.go
> +		Auth:          &secp256k1fx.Input{SigIndices: sigIndices},
And what about the case where we are creating a new alias? We don't have `in`.

2023-05-04 09:56 UTC, evlekht requested changes

2023-05-04 09:56 UTC, evlekht commented on vms/platformvm/txs/camino_multisig_alias_tx.go
> +	errFailedToVerifyAliasOrAuth            = fmt.Errorf("failed to verify alias or auth")
```suggestion
	errFailedToVerifyAliasOrAuth            = errors.New("failed to verify alias or auth")
```

2023-05-04 10:06 UTC, evlekht submitted a review, later dismissed

2023-05-04 13:51 UTC, peak3d requested changes

2023-05-04 13:51 UTC, peak3d commented on vms/platformvm/txs/executor/camino_helpers_test.go
> +type msgOwnersWIthKeys struct {
Typo

2023-05-04 13:51 UTC, peak3d commented on vms/platformvm/txs/executor/camino_tx_executor.go
> +	errAliasCredentialMissmatch     = errors.New("alias credential isn't matching")
Typo

2023-05-04 13:51 UTC, peak3d commented on vms/platformvm/txs/executor/camino_tx_executor.go
> +	// Update existing mutlisig definition
Typo

2023-05-04 15:53 UTC, peak3d approved these changes

2023-05-04 16:20 UTC, merged