[PVM] UnlockDepositTx and VerifyUnlockDepositedUTXOs refactoring
chain4travel/caminogo pull request #251
Opened 2023-05-05 15:02 UTC by evlekht

## Why this should be merged

## How this works

## How this was tested

2023-05-08 13:03 UTC, charalarg commented on vms/platformvm/utxo/camino_locked.go
> +			return fmt.Errorf("failed to verify transfer: %w", errUTXOOutTypeOrAmtMissmatch)
Typo: missmatch -> mismatch

2023-05-08 13:20 UTC, charalarg commented on vms/platformvm/utxo/camino_locked.go
> +			// Input is locked, but LockIDs isn't matching utxo's
Typo: isn't -> aren't

2023-05-09 12:36 UTC, charalarg requested changes

2023-05-09 12:36 UTC, charalarg commented on vms/platformvm/utxo/camino_locked.go
> +			return fmt.Errorf("failed to verify transfer: %w", errUTXOOutTypeOrAmtMissmatch)
Typo: errUTXOOutTypeOrAmtMissmatch -> errUTXOOutTypeOrAmtMismatch (Its also used in other places)

2023-05-09 12:36 UTC, charalarg commented on vms/platformvm/utxo/camino_locked.go
> +			// Input is locked, but LockIDs isn't matching utxo's
Typo: isn't -> aren't

2023-05-24 20:26 UTC, evlekht commented on vms/platformvm/utxo/camino_locked.go
> +			// Input is locked, but LockIDs isn't matching utxo's
well, LockIDs here is a single object

2023-05-31 13:04 UTC, c4t-ag requested changes

2023-05-31 13:04 UTC, c4t-ag commented on vms/platformvm/txs/executor/camino_tx_executor.go
> +	errUnlockedMoreThanAvailable      = errors.New("unlocked more deposited tokens, than was available for unlock")
remove comma pls.

2023-05-31 13:35 UTC, c4t-ag approved these changes

2023-05-31 13:40 UTC, charalarg approved these changes

2023-05-31 13:41 UTC, merged