Admin API DNS Rebinding mitigation
chain4travel/caminogo pull request #254
Opened 2023-05-11 16:56 UTC by DerTiedemann

New PR as #231 was merged to the wrong branch

## Why this should be merged
To fix a DNS rebinding attack against locally running node.
Camino node exposes the administrator functionality via /ext/admin RPC API endpoint. For example, it is possible to retrieve a private key of the node by sending the following payload:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method" : "admin.getNodeSigner"
}
```

While /ext/admin is disabled on public nodes, it is still possible to access
administrator endpoints from the internet via DNS rebinding when a node is
run locally. To do so, an attacker lures a victim with a running local Camino
node on an HTML page with a specially crafted JavaScript scenario. After
the victim visits the malicious page, A record in DNS settings is
automatically changed to resolve to the locally running node (127.0.0.1),
this page periodically sends admin.getNodeSigner HTTP requests to the
local node of the victim, and after some time the browser receives an
updated DNS information and starts to resolve a malicious domain to the
local node service thus bypassing Same Origin Policy. For example, in Safari
it takes roughly 10 minutes for the browser to fetch new DNS settings. In
Chrome there is a protection from this attack that explicitly forbids 127.0.0.1,
however it can be bypassed by setting 0.0.0.0 in the A record.
## How this works
This assumes the attacker has no control over the Host header of a sent address. (This could not be the case, please verify)
Now every request to the admin API needs to have the hostname that ist set in the `--http-host` flag. Otherwise requests will fail.
This is not optional.
## How this was tested
Added two new tests.

2023-06-06 14:37 UTC, knikos commented on api/admin/service.go
> +	host := strings.Split(hostName, ":")
the configured Host `config.HTTPHost` cannot include a port afaik. The request host `r.Request.Host` is the one that can contain a port.

2023-06-07 08:50 UTC, DerTiedemann commented on api/admin/service.go
> +	host := strings.Split(hostName, ":")
thats fine - the we will always hit the second case
this is here for completeness sake and if we decided to pass the port

2023-06-09 12:50 UTC, knikos commented
the flagset is missing the new Flag key --unsafe-api-admin-enabled

Something like the following should be added in `config/flags.go#addNodeFlags`

`fs.Bool(AdminAPIDisableSafeModeKey, false, "If true, this node exposes the Admin API without safe mode")`
Otherwise it prints the error
`couldn't configure flags: unknown flag: --unsafe-api-admin-enabled`

2023-06-09 12:53 UTC, knikos requested changes

2023-06-09 12:53 UTC, knikos commented on node/config.go
> +	UnsafeAdminAPIEnabled bool `json:"unsageAdminAPIEnabled"`
minor typo here: unsa**ge**AdminAPIEnabled

2023-06-09 13:07 UTC, DerTiedemann commented
> the flagset is missing the new Flag key --unsafe-api-admin-enabled
> 
> Something like the following should be added in `config/flags.go#addNodeFlags`
> 
> `fs.Bool(AdminAPIDisableSafeModeKey, false, "If true, this node exposes the Admin API without safe mode")` Otherwise it prints the error `couldn't configure flags: unknown flag: --unsafe-api-admin-enabled`

Resolved

2023-06-09 13:08 UTC, knikos approved these changes

2023-06-09 13:09 UTC, merged