[WIP :fire:] P2C CrossChain command execution - New TX
chain4travel/caminogo pull request #267
Opened 2023-06-22 05:18 UTC by DerTiedemann

- add structs/interfaces for commmands to work
- Command Sending Tx

## Why this should be merged

## How this works

## How this was tested

2023-06-22 09:38 UTC, evlekht requested changes

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/commands/camino_command_set_base_fee.go
> +	case cmd.BaseFee > 0:
thats the opposite

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/commands/camino_command_set_base_fee.go
> +	"github.com/ava-labs/coreth/core/state"
I don't think that its a good idea to make 2-way dependency between caminogo and caminoethvm (or one-way on avax-evm)

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/executor/atomic_tx_executor.go
> +func (e *AtomicTxExecutor) SendCommandTx(tx *txs.SendCommandTx) error {
that must go to camino executor

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/executor/proposal_tx_executor.go
> +func (*ProposalTxExecutor) SendCommandTx(*txs.SendCommandTx) error {
we have dedicated file for this, see camino visitor

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/executor/standard_tx_executor.go
> +func (*StandardTxExecutor) SendCommandTx(*txs.SendCommandTx) error {
we have dedicated file for this, see camino visitor

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/executor/tx_mempool_verifier.go
> +func (v *MempoolTxVerifier) SendCommandTx(tx *txs.SendCommandTx) error {
we have dedicated file for this, see camino visitor

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/mempool/issuer.go
> +func (i *issuer) SendCommandTx(*txs.SendCommandTx) error {
we have dedicated file for this, see camino visitor

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/mempool/remover.go
> +func (*remover) SendCommandTx(*txs.SendCommandTx) error {
we have dedicated file for this, see camino visitor

2023-06-22 09:38 UTC, evlekht commented on go.mod
> +	github.com/ava-labs/coreth v0.12.3
we shouldn't depend on avax evm, imo
its not as bad as if caminogo would depend on caminoethvm, but its still bad idea to depend on avax repository

2023-06-22 09:38 UTC, evlekht commented on vms/platformvm/txs/commands/camino_command_set_base_fee.go
> +func (cmd *CommandSetBaseFee) EVMStateTransfer(ctx *snow.Context, state *state.StateDB) error {
I think that its not right to have evm code in pvm
EVM stuff must be in evm, same true for any other vm

2023-07-07 01:53 UTC, DerTiedemann commented on go.mod
> +	github.com/ava-labs/coreth v0.12.3
this only pulls in a seperate package that has no relation to anything else from coreth. One could put everything into caminogo, but then we get duplicated code and codec madness. Lets discuss in a sync

2024-02-12 10:34 UTC, closed without merging