[PVM] Forbid nested msig aliases
chain4travel/caminogo pull request #272
Opened 2023-07-20 17:05 UTC by evlekht

## Why this should be merged
We want don't want to support nested multisig aliases. This PR forbids adding new nested multisig aliases or adding multisig alias addresses to existing multisig aliases.
## How this works
MultisigAliasesTx checks each multisig alias address that its not existing multisig alias.
## How this was tested
Unit-tests.

2023-07-21 07:23 UTC, knikos submitted a review, later dismissed
LGTM

2023-07-21 11:50 UTC, c4t-ag requested changes
Hi, we already have an "nested check" function somewhere.
I suggest to have only one instead code duplication here.

2023-07-21 20:19 UTC, evlekht commented
> Hi, we already have an "nested check" function somewhere. I suggest to have only one instead code duplication here.

IRRC we have check in spend verify for output owners. So, its checking avax control groups that owns produced outs. We don't have any check for newly created alias in this tx. Also, existing check allows nesting, irrc, but forbids cycling. But we want to forbid nesting completely

2023-09-27 08:34 UTC, peak3d commented
@evlekht I'm refering to: https://github.com/chain4travel/caminogo/blob/dev/vms/platformvm/utxo/camino_locked.go#L1250
I think we should merge the 2 things (this PR and the mentioned function). One solution could be extracting the inner part (the loop over owner addresses) into a new function, and call this new function from PR and existing function.

I really want to avoid, that we have this temporary restriction implemented on 2 different places.

2023-09-28 15:05 UTC, peak3d approved these changes

2023-09-28 15:07 UTC, c4t-ag approved these changes
Nice, thx!

2023-09-29 11:09 UTC, merged