fix license headers
chain4travel/caminogo pull request #353
Opened 2024-07-23 17:45 UTC by evlekht

## Why this should be merged
to use camino-license instead of go-license to check license headers

## How this works
camino-license check --config=header.yaml <files>

## How this was tested
run ./scripts/lint.sh

## Additional references
Original PR based on cortina-19 dev
https://github.com/chain4travel/caminogo/pull/342

2024-07-24 12:24 UTC, mo-c4t requested changes

2024-07-24 12:24 UTC, mo-c4t commented on header.yaml
> +      // Copyright (C) 2019-2023, Ava Labs, Inc. All rights reserved.
remove 2023 and add {YEAR}

2024-07-24 13:26 UTC, evlekht commented on header.yaml
> +      // Copyright (C) 2019-2023, Ava Labs, Inc. All rights reserved.
but it will start failing then, because all avax headers are still 2023 in cortina 15

2024-07-24 13:33 UTC, mo-c4t commented on header.yaml
> +      // Copyright (C) 2019-2023, Ava Labs, Inc. All rights reserved.
ah I thought we will the license headers from avax too. okay, I will resolve it.

2024-07-24 13:33 UTC, mo-c4t submitted a review, later dismissed

2024-07-25 13:12 UTC, mo-c4t approved these changes

2024-07-25 13:13 UTC, merged