Feature-440: Add unit tests for camino genesis validtation
chain4travel/caminogo pull request #98
Opened 2022-12-07 11:44 UTC by charalarg

2022-12-10 11:23 UTC, c4t-ag commented on vms/platformvm/state/camino_deposit_offer_test.go
> +	require.Equal(t, depositOffers, []*deposit.Offer{&newDepositOffer, &genesisDepositOffer})
GetAllDepositOffers are unsorted! Need to sort before check.

2022-12-16 17:42 UTC, evlekht requested changes

2022-12-16 17:42 UTC, evlekht commented on genesis/genesis_camino_test.go
> +func TestValidateCaminoConfig(t *testing.T) {
may be its better to move those test to dedicated offer.Verify test?

2022-12-16 17:42 UTC, evlekht commented on vms/platformvm/state/camino_deposit_offer_test.go
> +		"Happy path": {
add offer was deleted case

2022-12-16 17:42 UTC, evlekht commented on vms/platformvm/state/camino_deposit_offer_test.go
> +func TestGetAllDepositOffers(t *testing.T) {
that doesn't test anything related to db/diff

2023-03-30 09:38 UTC, closed without merging